dependency checks: removed imagemagick again, added img viewer check

diff --git a/kunst b/kunst
--- a/kunst
+++ b/kunst
@@ -190,13 +190,25 @@ pre_exit() {
 
 main() {
 
-    dependencies=(sxiv convert bash ffmpeg mpc jq mpd)
-    for dependency in "${dependencies[@]}"; do
-        type -p "$dependency" &>/dev/null || {
-            echo "error: Could not find '${dependency}', is it installed?" >&2
-            exit 1
-        }
-    done
+	dependencies=(bash ffmpeg mpc jq mpd)
+	for dependency in "${dependencies[@]}"; do
+		type -p "$dependency" &>/dev/null || {
+			echo "error: Could not find '${dependency}', is it installed?" >&2
+			exit 1
+		}
+	done
+
+	if [ "$VIEWER" == 'sxiv' ]; then
+		type -p "sxiv" &>/dev/null || {
+			echo "error: could not find sxiv" >&2
+			exit 1
+		}
+	elif [ "$VIEWER" == 'imv' ]; then
+		type -p "imv" &>/dev/null || {
+			echo "error: could not find imv" >&2
+			exit 1
+		}
+	fi
 
     [ "$KUNST_MUSIC_DIR" != "" ] && MUSIC_DIR="$KUNST_MUSIC_DIR"
     [ "$KUNST_SIZE" != "" ] && SIZE="$KUNST_SIZE"
